### PR TITLE
Digital gates

### PR DESCRIPTION
**Pull request by ouabache**
Here is my initial release for a digital parts library. It consists of:

14 Motorola 74ls parts in both dip and soic packages
datasheet pdfs from Motorola.
Basic logic gates in 4 different scales
a collection of other useful logic building blocks

### CODE REVIEW

**Comment by ubruhin** [comment]
Wow, that's a lot to review! :astonished: 

My comments so far:

- Datasheets should not be added to the library (they can't be referenced by library elements anyway, so they only waste space).
- To be honest, I don't see the reason why some symbols are added in many different sizes. What's the advantage of the "small", "medium" or "default" symbols compared to "tiny"? -> I would remove all except "tiny".
- Pin length varies from 2.54mm up to 10.16mm -> they should all be 2.54mm, longer pins have no advantage.
- The symbols `POWER_BLK` and `POWER_BLK_VCC` aren't needed, in the Base library there is already the symbol `Generic Power Connection 2-Pin` which should be used for this purpose.
- Some names are a bit "cryptic" (like `DFF_RNPN`, `AND2_dm_4`, ...) -> Generally we use human readable names, i.e. without underscores and abbreviations (if it doesn't get too long).
- The pin placement of the 74xx symbols is not really according [our conventions](https://docs.librepcb.org/#libraryconventions-symbols-pinplacement) (no pins at top/bottom, preferred spacing of 2.54mm).
- There shouldn't be text labels on the Outlines layer which describe the functionality of the IC - the functionality should be clear by the VALUE anyway (if not, the user could adjust the VALUE by himself).
- Splitting the PR into several smaller PRs might simplify reviewing all the new library elements ;)

**Comment by ouabache** [comment]
On Sun, Sep 8, 2019 at 12:41 PM U. Bruhin <notifications@github.com> wrote:

> Wow, that's a lot to review! 😲
>
> My comments so far:
>
>    - Datasheets should not be added to the library (they can't be
>    referenced by library elements anyway, so they only waste space).
>
>
I will delete them

>
>    - To be honest, I don't see the reason why some symbols are added in
>    many different sizes. What's the advantage of the "small", "medium" or
>    "default" symbols compared to "tiny"? -> I would remove all except "tiny".
>
>
And another engineer will  be happy using the default size. No matter what
size you pick ,somebody will not like it. So I offer the entire range and
let each engineer choose their own size. The beauty of LibrePCB's variants
is that you can do that for free. We do want to show off any features that
Kicad doesn't support. It will make them think.

>
>    - Pin length varies from 2.54mm up to 10.16mm -> they should all be
>    2.54mm, longer pins have no advantage.
>
> That's an artifact from how I generated the symbols. I'm not crazy enough
to hand enter all those symbols. I created one gate that was 4X size and
then made 4 copies. I then edited the properties of each one dividing each
number by a constant. The constants were 4,5,6 and 8 to produce
default,medium,small and tiny. The gate graphics usually do not wind up on
a snap grid but the end of the pin has to. This means that the pin length
has to vary to bridge the gap. I also allow an extra 2.54 for a inversion
bubble in case that is used.

Default size has a footprint of 12 snap grids to match kicad's libraries.
Medium has 10,small has 8 and tiny has 6.





>
>    - The symbols POWER_BLK and POWER_BLK_VCC aren't needed, in the Base
>    library there is already the symbol Generic Power Connection 2-Pin
>    which should be used for this purpose.
>
> I can use that. I wasn't thrilled about having pin names of 1,2 instead of
vcc,gnd.



>
>    - Some names are a bit "cryptic" (like DFF_RNPN, AND2_dm_4, ...) ->
>    Generally we use human readable names, i.e. without underscores and
>    abbreviations (if it doesn't get too long).
>
>
Old habits die hard. That is how IC designers pick names. I will change
them.


>
>    - The pin placement of the 74xx symbols is not really according our
>    conventions
>    <https://docs.librepcb.org/#libraryconventions-symbols-pinplacement>
>    (no pins at top/bottom, preferred spacing of 2.54mm).
>
>
I will move the top,bottom pins to the sides. Is it ok to have a vertical
spacing of 5.08 in order to separate the gates within the package?


>
>    - There shouldn't be text labels on the Outlines layer which describe
>    the functionality of the IC - the functionality should be clear by the
>    VALUE anyway (if not, the user could adjust the VALUE by himself).
>
> I will remove them



>    - Splitting the PR into several smaller PRs might simplify reviewing
>    all the new library elements ;)
>
> i was considering placing all the logic gates into their own repository to
keep from mixing board components with logic blocks. That would simplify
things
I also have a repo in ouabache called LibrePCB_FPGA_Lattice_ICE_40.lplib
that contains all the parts supported by the icestorm project. You can pull
that over and add it as well.

John Eaton

**Comment by ouabache** [comment]
I am also considering changing the gate output name from OUT to Y.

**Comment by ouabache** [comment]
I have checked in some fixes. See if this will work now.

John Eaton

**Pull request closed without merging**
