### PR TITLE
Add sym/cmp for schmitt triggers

### PR DESCRIPTION
**Pull request by dbrgn**
Both inverting and non-inverting versions.

Inverting:

screenshot

Non-inverting:

screenshot

### CODE REVIEW

**Comment by ubruhin** [comment]
Symbol/Component Names:
- Use title case
- Put "Inverted" / "Non-Inverted" to the end (i.e. start with "Schmitt Trigger") to have them next to each other in a sorted list

Symbols:
- Rename pins to IN, OUT, V+, V- (these aren't generic symbols, so their pin functionality is known)
- According [Wikipedia](https://en.wikipedia.org/wiki/Schmitt_trigger), the hysteresis symbol should be the other way around for the non-inverting symbol (although I don't know it this is commonly accepted practice).
- Disable grab area for the circle (I would say it's not part of the "body", but part of the pin).
- Maybe shorten the OUT pin by 2.54mm?
- Maybe decrease body width by 2.54mm? See Eagle symbol: 
grafik

Components:
- Set default value to "{{PARTNUMBER or DEVICE}}"
- Maybe rename signals to IN, OUT, V+, V-

**Comment by dbrgn** [comment]
> Use title case
> Put "Inverted" / "Non-Inverted" to the end (i.e. start with "Schmitt Trigger") to have them next to each other in a sorted list

Done

> According Wikipedia, the hysteresis symbol should be the other way around for the non-inverting symbol (although I don't know it this is commonly accepted practice).

You probably mean [this illustration](https://en.wikipedia.org/wiki/Schmitt_trigger#/media/File:Schmitt_trigger_inverted_symbol.svg)? No, those are two variants I think. Note that one of them has an inverted symbol, while the other one has a bubble. See also this description:

img

I'd go with non-inverted + bubble, the other one seems like double inversion to me :slightly_smiling_face: 

> Disable grab area for the circle (I would say it's not part of the "body", but part of the pin).
> Maybe shorten the OUT pin by 2.54mm?
> Maybe decrease body width by 2.54mm? See Eagle symbol:

Done

**Comment by ubruhin** [comment]
> > Use title case
> > Put "Inverted" / "Non-Inverted" to the end (i.e. start with "Schmitt Trigger") to have them next to each other in a sorted list
>
> Done

Still not done for the Components ;)

Everything else looks good now :+1:

> You probably mean this illustration? No, those are two variants I think. Note that one of them has an inverted symbol, while the other one has a bubble. See also this description:

Oh, probably I read the German Wikipedia which I interpreted in a different way:
grafik

Now I'm confused totally :grin: Probably it's OK the way you did it :)

**Comment by dbrgn** [comment]
> Still not done for the Components ;)

Whoops, good catch. Missed those. Fixed now.

The German Wikipedia doesn't make sense to me at all :slightly_smiling_face:

**Comment by ubruhin** [comment]
Perfect, thanks :)

**Pull request merged**
