### PR TITLE
Added Optocoupler symbol

### PR DESCRIPTION
**Pull request by pinoaffe**
I added a symbol for optocouplers with transistor output, such as the 6N136
depends on https://github.com/LibrePCB-Libraries/LibrePCB_Base.lplib/pull/25

### CODE REVIEW

**Comment by ubruhin** [comment]
Generally it looks good so far, but IMHO the symbol looks a bit large. So I took a look at Eagle libraries, there it has a more compact look:

grafik

I like it (saves 2*2.54mm in height), what do you think?

**Comment by pinoaffe** [comment]
sure, looks good

**Comment by pinoaffe** [comment]
this is more similar to what you posted, does it look okay?
2019-04-10-101258_613x536_scrot

**Comment by ubruhin** [comment]
Perfect, thanks! :+1:

**Pull request merged**
